modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="sable_cc_tick_sync"
version="${version}"
displayName="Sable CC Tick Sync"
authors="Ivan"
description='''Synchronizes CC:Tweaked computers on Sable constructions with Sable physics substeps and provides an optional +100 Hz mode.'''

[[mixins]]
config="sable_cc_tick_sync.mixins.json"

[[dependencies.sable_cc_tick_sync]]
modId="neoforge"
type="required"
versionRange="[21.1.248,22)"
ordering="NONE"
side="SERVER"

[[dependencies.sable_cc_tick_sync]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="SERVER"

[[dependencies.sable_cc_tick_sync]]
modId="sable"
type="required"
versionRange="[${sable_version},2.0.6)"
ordering="AFTER"
side="SERVER"

[[dependencies.sable_cc_tick_sync]]
modId="computercraft"
type="required"
versionRange="[1.120.0,1.121.0)"
ordering="AFTER"
side="SERVER"
